// Sample products for the Sajiri ecommerce platform
const sampleProducts = [
  // Women's Collection
  {
    name: 'Classic White Cotton T-Shirt',
    description: 'Premium quality white cotton t-shirt perfect for everyday wear. Comfortable and durable.',
    category: 'Women',
    price: 599,
    discountPrice: 399,
    stock: 50,
    mainImage: 'https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg',
    images: [],
    isFeatured: true,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Tops',
    brand: 'Sajiri Premium',
    fabric: 'Cotton',
    color: 'White',
  },
  {
    name: 'Blue Denim Jeans',
    description: 'Stylish blue denim jeans with perfect fit. Great for casual and semi-formal occasions.',
    category: 'Women',
    price: 1299,
    discountPrice: 899,
    stock: 35,
    mainImage: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg',
    images: [],
    isFeatured: true,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Bottoms',
    brand: 'Denim Co',
    fabric: 'Denim',
    color: 'Blue',
  },
  {
    name: 'Black Yoga Leggings',
    description: 'Comfortable black yoga leggings with high waist support. Perfect for gym and yoga sessions.',
    category: 'Women',
    price: 899,
    discountPrice: 599,
    stock: 40,
    mainImage: 'https://images.pexels.com/photos/4662438/pexels-photo-4662438.jpeg',
    images: [],
    isFeatured: false,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Activewear',
    brand: 'Fit Active',
    fabric: 'Polyester',
    color: 'Black',
  },
  {
    name: 'Floral Summer Dress',
    description: 'Beautiful floral printed summer dress. Perfect for casual outings and beach wear.',
    category: 'Women',
    price: 1499,
    discountPrice: 999,
    stock: 25,
    mainImage: 'https://images.pexels.com/photos/994523/pexels-photo-994523.jpeg',
    images: [],
    isFeatured: true,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Dresses',
    brand: 'Summer Styles',
    fabric: 'Cotton',
    color: 'Multi',
  },
  {
    name: 'Red Hoodie Sweatshirt',
    description: 'Cozy red hoodie perfect for cold weather. Soft and warm with comfortable fit.',
    category: 'Women',
    price: 1099,
    discountPrice: 799,
    stock: 30,
    mainImage: 'https://images.pexels.com/photos/6311650/pexels-photo-6311650.jpeg',
    images: [],
    isFeatured: false,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Hoodies',
    brand: 'Cozy Wear',
    fabric: 'Fleece',
    color: 'Red',
  },
  
  // Men's Collection
  {
    name: 'Classic Black T-Shirt',
    description: 'Premium black t-shirt for men. Versatile and perfect for any casual outfit.',
    category: 'Men',
    price: 549,
    discountPrice: 349,
    stock: 60,
    mainImage: 'https://images.pexels.com/photos/428340/pexels-photo-428340.jpeg',
    images: [],
    isFeatured: true,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Tops',
    brand: 'Sajiri Premium',
    fabric: 'Cotton',
    color: 'Black',
  },
  {
    name: 'Navy Blue Formal Shirt',
    description: 'Navy blue formal shirt perfect for office and business meetings. Premium quality fabric.',
    category: 'Men',
    price: 1399,
    discountPrice: 999,
    stock: 28,
    mainImage: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg',
    images: [],
    isFeatured: false,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Formal',
    brand: 'Office Pro',
    fabric: 'Cotton',
    color: 'Navy',
  },
  {
    name: 'Gray Sports Shorts',
    description: 'Comfortable gray sports shorts for running and gym. Breathable and quick-dry.',
    category: 'Men',
    price: 699,
    discountPrice: 449,
    stock: 45,
    mainImage: 'https://images.pexels.com/photos/936075/pexels-photo-936075.jpeg',
    images: [],
    isFeatured: false,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Activewear',
    brand: 'Sports Max',
    fabric: 'Polyester',
    color: 'Gray',
  },
  {
    name: 'Dark Blue Chinos',
    description: 'Stylish dark blue chino pants for semi-formal occasions. Perfect fit and comfort.',
    category: 'Men',
    price: 1199,
    discountPrice: 849,
    stock: 32,
    mainImage: 'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg',
    images: [],
    isFeatured: true,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Bottoms',
    brand: 'Smart Wear',
    fabric: 'Cotton',
    color: 'Navy',
  },
  {
    name: 'Gray Zip-up Jacket',
    description: 'Stylish gray zip-up jacket for winters. Warm and versatile for casual wear.',
    category: 'Men',
    price: 1599,
    discountPrice: 1199,
    stock: 22,
    mainImage: 'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg',
    images: [],
    isFeatured: false,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Jackets',
    brand: 'Winter Style',
    fabric: 'Polyester',
    color: 'Gray',
  },
  
  // Kids' Collection
  {
    name: 'Colorful Kids T-Shirt',
    description: 'Bright colorful t-shirt for kids. Soft and comfortable for daily wear.',
    category: 'Kids',
    price: 399,
    discountPrice: 249,
    stock: 70,
    mainImage: 'https://images.pexels.com/photos/3662667/pexels-photo-3662667.jpeg',
    images: [],
    isFeatured: true,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Tops',
    brand: 'Kids Fun',
    fabric: 'Cotton',
    color: 'Multi',
  },
  {
    name: 'Blue Denim Shorts',
    description: 'Comfortable blue denim shorts for kids. Perfect for play and casual occasions.',
    category: 'Kids',
    price: 549,
    discountPrice: 349,
    stock: 55,
    mainImage: 'https://images.pexels.com/photos/3933274/pexels-photo-3933274.jpeg',
    images: [],
    isFeatured: false,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Bottoms',
    brand: 'Kids Wear',
    fabric: 'Denim',
    color: 'Blue',
  },
  {
    name: 'Pink Cute Dress',
    description: 'Adorable pink dress for girls with cute patterns. Perfect for parties and special occasions.',
    category: 'Kids',
    price: 799,
    discountPrice: 499,
    stock: 38,
    mainImage: 'https://images.pexels.com/photos/1620760/pexels-photo-1620760.jpeg',
    images: [],
    isFeatured: true,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Dresses',
    brand: 'Cute Kids',
    fabric: 'Cotton',
    color: 'Pink',
  },
  {
    name: 'Green Printed Hoodie',
    description: 'Fun green hoodie for kids with cool prints. Warm and cozy for cold weather.',
    category: 'Kids',
    price: 699,
    discountPrice: 449,
    stock: 42,
    mainImage: 'https://images.pexels.com/photos/3770588/pexels-photo-3770588.jpeg',
    images: [],
    isFeatured: false,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Hoodies',
    brand: 'Cozy Kids',
    fabric: 'Fleece',
    color: 'Green',
  },
  {
    name: 'Sports Track Pants',
    description: 'Comfortable track pants for active kids. Great for sports and outdoor activities.',
    category: 'Kids',
    price: 649,
    discountPrice: 399,
    stock: 48,
    mainImage: 'https://images.pexels.com/photos/3933274/pexels-photo-3933274.jpeg',
    images: [],
    isFeatured: false,
    status: 'approved',
    sellerName: 'Sajiri Store',
    subCategory: 'Activewear',
    brand: 'Active Kids',
    fabric: 'Polyester',
    color: 'Black',
  },
];

module.exports = sampleProducts;
